version: '3'

services:
  frontend:
    # Specify the build context for the frontend
    build:
      context: ./frontend
    # Map the host port to the container port
    ports:
      - "3000:3000"
    # Specify dependencies (if applicable)
    depends_on:
      - backend

  backend:
    # Specify the build context for the backend
    build:
      context: ./backend
    # Map the host port to the container port
    ports:
      - "5000:5000"