# This is just a template placeholder docker-compose file. Use relevant sections which are applicable, 
# and feel free to customize.
version: '3'

services:
  frontend:
    # Specify the build context for the frontend
    build:
      context: ./frontend
    # Map the host port to the container port
    ports:
      - "3000:3000"
    # Specify dependencies (if applicable)
    depends_on:
      - backend

    # Additional options (uncomment and configure as needed):
    
    # Specify environment variables if needed
    environment:
      - REACT_APP_API_URL=http://backend:5000

  backend:
    # Specify the build context for the backend
    build:
      context: ./backend
    # Map the host port to the container port
    ports:
      - "5000:5000"
    
    # Additional options (uncomment and configure as needed):
    
    # Specify environment variables if needed
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development