# TODO: Define the Workflow Name
name: CI/CD Pipeline

# TODO: Define triggers for the workflow
on:
   push:
     branches: [main]
   pull_request:
     branches: [main]

jobs:
  # TODO: Define a job for building and testing the frontend
  frontend:
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
      # TODO: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      # TODO: Install dependencies
    - name: Install dependencies
      run: |
        cd frontend
        npm install
      # TODO: Run tests
    - name: Run tests
      run: |
        cd frontend
        npm test
      # TODO: Build the React app
    - name: Build the React app
      run: |
        cd frontend
        npm run build

  # TODO: Define a job for building and testing the backend
  backend:
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
      # TODO: Setup Python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
      # TODO: Install dependencies
    - name: Install dependencies
      run: |
        cd backend
        pip install -r requirements.txt
      # TODO: Run tests
    - name: Run tests
      run: |
        cd backend
        pytest

  # TODO: Define a job for building and pushing Docker images
  docker:
    # Run this job only when 'frontend' & 'backend' stages are sucessfully completed
    needs: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
      # TODO: Setup Docker
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2
      # TODO: Build frontend Docker image
    - name: Build frontend Docker image
      run: docker build -t frontend:latest frontend
      # TODO: Build backend Docker image
    - name: Build backend Docker image
      run: docker build -t backend:latest backend
      # TODO: Push images to Docker Hub (if on main branch)
    - name: Push images to Docker Hub
      run: |
        if [ ${{ github.ref }} = 'refs/heads/main' ]; then
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag frontend:latest jaucoin29/devops:frontend
          docker push jaucoin29/devops:frontend
          docker tag backend:latest jaucoin29/devops:backend
          docker push jaucoin29/devops:backend
        fi